import { StructureKind, Project } from 'ts-morph';

import { DEFAULT_LANGUAGE_TOKEN_TYPE_STR, AUTOGENERATED_CODE_COMMENT_STR, GENERATIONS_TARGET_FOLDER, DEFAULT_LANGUAGE_KEY } from '../../config';

export default async function generateDefaultLanguageTokenType(
  __TOKEN: string = DEFAULT_LANGUAGE_KEY,
  __DEFAULT_LANGUAGE_TOKEN_TYPE_STR: string = DEFAULT_LANGUAGE_TOKEN_TYPE_STR,
  __TARGET_FOLDER: string = GENERATIONS_TARGET_FOLDER
) {
  const project = new Project();

  const sourceFile = project.createSourceFile(
    `${__TARGET_FOLDER}/${__DEFAULT_LANGUAGE_TOKEN_TYPE_STR}.ts`,
    {
      statements: [
        {
          name: __DEFAULT_LANGUAGE_TOKEN_TYPE_STR,
          kind: StructureKind.TypeAlias,
          type: '"' + __TOKEN + '"',
          isExported: false
        }
      ]
    },
    { overwrite: true }
  );
  const oldTextLength = sourceFile.getText().length;

  sourceFile.insertText(0, AUTOGENERATED_CODE_COMMENT_STR);
  sourceFile.insertText(oldTextLength + AUTOGENERATED_CODE_COMMENT_STR.length, `export default ${__DEFAULT_LANGUAGE_TOKEN_TYPE_STR};\n`);
  await sourceFile.save();
}
