import { StructureKind, Project } from 'ts-morph';

import type { CategoriesMetadatas } from '../../types/metadatas';

import { AUTOGENERATED_CODE_COMMENT_STR, TS_MORPH_FORMATTER_SETTINGS, GENERATIONS_TARGET_FOLDER, BLOG_TYPE_STR } from '../../config';

export default function generateBlogType(blogArchitecture: CategoriesMetadatas) {
  const project = new Project();

  const sourceFile = project.createSourceFile(
    `${GENERATIONS_TARGET_FOLDER}/${BLOG_TYPE_STR}.ts`,
    {
      statements: [
        {
          type: JSON.stringify(blogArchitecture, (_, v) => (Array.isArray(v) ? v.map((slug) => `'${slug}'`).join(' | ') : v), 2).replace(
            /"'|'"/g,
            "'"
          ),
          kind: StructureKind.TypeAlias,
          name: BLOG_TYPE_STR,
          isExported: false
        }
      ]
    },
    { overwrite: true }
  );
  const oldTextLength = sourceFile.getText().length;

  sourceFile.insertText(0, AUTOGENERATED_CODE_COMMENT_STR);
  sourceFile.insertText(oldTextLength + AUTOGENERATED_CODE_COMMENT_STR.length, `export default ${BLOG_TYPE_STR};`);
  sourceFile.formatText(TS_MORPH_FORMATTER_SETTINGS);
  sourceFile.saveSync();
}
