import { StructureKind, Project } from 'ts-morph';

import type { CategoriesMetadatas } from '../../types/Metadatas';

import { AUTOGENERATED_CODE_COMMENT_STR, TS_MORPH_FORMATTER_SETTINGS, GENERATIONS_TARGET_FOLDER, BLOG_TYPE_STR } from '../../config';

export default async function generateBlogType(
  blogArchitecture: CategoriesMetadatas,
  pretty: boolean,
  __BLOG_TYPE_STR: string = BLOG_TYPE_STR,
  __TARGET_FOLDER: string = GENERATIONS_TARGET_FOLDER
) {
  const project = new Project();

  const sourceFile = project.createSourceFile(
    `${__TARGET_FOLDER}/${__BLOG_TYPE_STR}.ts`,
    {
      statements: [
        {
          type: JSON.stringify(
            blogArchitecture,
            (_, v) => (Array.isArray(v) ? v.map((slug) => `'${slug}'`).join('|') : v),
            pretty ? 2 : undefined
          ).replace(/"'|'"/g, "'"),
          kind: StructureKind.TypeAlias,
          name: __BLOG_TYPE_STR,
          isExported: false
        }
      ]
    },
    { overwrite: true }
  );
  const oldTextLength = sourceFile.getText().length;

  sourceFile.insertText(0, AUTOGENERATED_CODE_COMMENT_STR);
  sourceFile.insertText(oldTextLength + AUTOGENERATED_CODE_COMMENT_STR.length, `export default ${__BLOG_TYPE_STR};`);
  if (pretty) sourceFile.formatText(TS_MORPH_FORMATTER_SETTINGS);
  await sourceFile.save();
}
