import type { WriterFunction } from 'ts-morph';

import { StructureKind, Project, Writers } from 'ts-morph';

import type { CategoriesMetadatas } from '../../types/metadatas';

import { AUTOGENERATED_CODE_COMMENT_STR, TS_MORPH_FORMATTER_SETTINGS, BLOG_ARCHITECTURE_TYPE_STR, GENERATIONS_TARGET_FOLDER } from '../../config';

export default function generateBlogArchitectureType(blogArchitecture: CategoriesMetadatas) {
  const project = new Project();

  const writerFunction: WriterFunction = Writers.objectType({
    properties: Object.entries(blogArchitecture).map(([category, subcategories]) => ({
      type: Object.keys(subcategories)
        .map((subcategory) => `'${subcategory}'`)
        .join(' | '),
      name: `'${category}'`
    }))
  });

  const sourceFile = project.createSourceFile(
    `${GENERATIONS_TARGET_FOLDER}/${BLOG_ARCHITECTURE_TYPE_STR}.ts`,
    {
      statements: [
        {
          name: BLOG_ARCHITECTURE_TYPE_STR,
          kind: StructureKind.TypeAlias,
          type: writerFunction,
          isExported: false
        }
      ]
    },
    { overwrite: true }
  );
  const oldTextLength = sourceFile.getText().length;

  sourceFile.insertText(0, AUTOGENERATED_CODE_COMMENT_STR);
  sourceFile.insertText(oldTextLength + AUTOGENERATED_CODE_COMMENT_STR.length, `export default ${BLOG_ARCHITECTURE_TYPE_STR};`);
  sourceFile.formatText(TS_MORPH_FORMATTER_SETTINGS);
  sourceFile.saveSync();
}
